appName: SCORES-MANAGER-UI-PYSIDE
appShortName: SMGR
logLevel: WARN
authors:
  - Andrey Potapov
  - Sergei Boikov  

paths:
  workingpath: 'D:\-=Video convertation=-\temp'
  excluded_paths: ''

flags:
  debugmode: False

databases:
  postgres:
    host: rc1a-yllcr299ehv5rd4a.mdb.yandexcloud.net
    port: 6432
    sslmode: verify-full
    dbname: ScoresManagerDB
    user: mentor
    username: mentor
    target_session_attrs: read-write    
    password: TODO #get from env variable 


  